[[redirects]]
from = "/github"
to = "https://github.com/remusa"

[[redirects]]
from = "/linkedin"
to = "https://www.linkedin.com/in/remusa"

[[redirects]]
from = "/twitter"
to = "https://twitter.com/remusa_"
