[build]
  command = "pnpm run build"
  publish = "dist"

[[redirects]]
  from = "/github"
  to = "https://github.com/remusa"

[[redirects]]
  from = "/linkedin"
  to = "https://www.linkedin.com/in/remusa"
