import type { ProjectObjects, Site, SocialObjects, TechObjects } from "./types";

export const SITE: Site = {
	website: "https://renems.com",
	author: "René MS",
	desc: "Personal website.",
	title: "René MS",
	ogImage: "astropaper-og.jpg",
	lightAndDarkMode: true,
	postPerPage: 3,
};

export const LOCALE = ["en-EN"]; // set to [] to use the environment default

export const LOGO_IMAGE = {
	enable: true,
	svg: false,
	width: 40,
	height: 40,
};

export const SOCIALS: SocialObjects = [
	{
		name: "Mail",
		href: "mailto:yourmail@gmail.com",
		linkTitle: `Send an email to ${SITE.title}`,
		active: false,
	},
	{
		name: "Github",
		href: "https://renems.com/github",
		linkTitle: ` ${SITE.title} on Github`,
		active: true,
	},
	{
		name: "LinkedIn",
		href: "https://renems.com/linkedin",
		linkTitle: `${SITE.title} on LinkedIn`,
		active: true,
	},
	{
		name: "Facebook",
		href: "https://renems.com/facebook",
		linkTitle: `${SITE.title} on Facebook`,
		active: false,
	},
	{
		name: "Instagram",
		href: "https://renems.com/instagram",
		linkTitle: `${SITE.title} on Instagram`,
		active: false,
	},
	{
		name: "Twitter",
		href: "https://renems.com/twitter",
		linkTitle: `${SITE.title} on Twitter`,
		active: false,
	},
	{
		name: "Twitch",
		href: "https://renems.com/twitch",
		linkTitle: `${SITE.title} on Twitch`,
		active: false,
	},
	{
		name: "YouTube",
		href: "https://renems.com/youtube",
		linkTitle: `${SITE.title} on YouTube`,
		active: false,
	},
	{
		name: "WhatsApp",
		href: "https://renems.com/whatsapp",
		linkTitle: `${SITE.title} on WhatsApp`,
		active: false,
	},
	{
		name: "Snapchat",
		href: "https://renems.com/snapchat",
		linkTitle: `${SITE.title} on Snapchat`,
		active: false,
	},
	{
		name: "Pinterest",
		href: "https://renems.com/pinterest",
		linkTitle: `${SITE.title} on Pinterest`,
		active: false,
	},
	{
		name: "TikTok",
		href: "https://renems.com/tiktok",
		linkTitle: `${SITE.title} on TikTok`,
		active: false,
	},
	{
		name: "CodePen",
		href: "https://renems.com/codepen",
		linkTitle: `${SITE.title} on CodePen`,
		active: false,
	},
	{
		name: "Discord",
		href: "https://renems.com/discord",
		linkTitle: `${SITE.title} on Discord`,
		active: false,
	},
	{
		name: "GitLab",
		href: "https://renems.com/gitlab",
		linkTitle: `${SITE.title} on GitLab`,
		active: false,
	},
	{
		name: "Reddit",
		href: "https://renems.com/reddit",
		linkTitle: `${SITE.title} on Reddit`,
		active: false,
	},
	{
		name: "Skype",
		href: "https://renems.com/skype",
		linkTitle: `${SITE.title} on Skype`,
		active: false,
	},
	{
		name: "Steam",
		href: "https://renems.com/steam",
		linkTitle: `${SITE.title} on Steam`,
		active: false,
	},
	{
		name: "Telegram",
		href: "https://renems.com/telegram",
		linkTitle: `${SITE.title} on Telegram`,
		active: false,
	},
	{
		name: "Mastodon",
		href: "https://renems.com/mastodon",
		linkTitle: `${SITE.title} on Mastodon`,
		active: false,
	},
];

export const TECH: TechObjects = [
	{
		imagePath: "javascript.webp",
		altText: "javascript",
		active: true,
	},
	{
		imagePath: "typescript.webp",
		altText: "typescript",
		active: true,
	},
	{
		imagePath: "react.png",
		altText: "react",
		active: true,
	},
	{
		imagePath: "svelte.png",
		altText: "svelte",
		active: true,
	},
	{
		imagePath: "node.png",
		altText: "node",
		active: true,
	},
	{
		imagePath: "graphql.png",
		altText: "graphql",
		active: true,
	},
	{
		imagePath: "python.png",
		altText: "python",
		active: true,
	},
	{
		imagePath: "docker.webp",
		altText: "docker",
		active: false,
	},
	{
		imagePath: "postgresql.png",
		altText: "postgresql",
		active: false,
	},
	{
		imagePath: "next.png",
		altText: "next.js",
		active: true,
	},
];

export const PROJECTS: ProjectObjects = [
	{
		title: "Cero",
		active: false,
		description:
			"Cero is an intermittent fasting tracker built in React, Node and GraphQL.",
		type: ["fullstack", "react", "node", "graphql", "typescript"],
		tech: ["React", "TypeScript", "Node", "GraphQL"],
		ogImage: "cero.png",
		url: "https://cero.netlify.com",
		repository: "https://github.com/remusa/cero",
		featured: true,
	},
	{
		title: "Does it break fast?",
		active: true,
		description:
			"A web app that helps checking whether some kind of food breaks a fasting period.",
		type: ["fullstack", "react", "firebase"],
		tech: ["React", "Next.js", "TypeScript", "Firebase"],
		ogImage: "doesitbreakfast.png",
		url: "https://doesitbreakfast.now.sh",
		repository: "https://github.com/remusa/oesitbreakfast",
		featured: true,
	},
	{
		title: "Personal website",
		active: true,
		description: "This site!, developed using Astro.",
		type: ["react", "graphql"],
		tech: ["Astro"],
		ogImage: "gatsby-portfolio.png",
		url: "https://renems.com",
		repository: "https://github.com/remusa/ortfolio",
		featured: true,
	},
	{
		title: "Pomodoro Clock",
		active: true,
		description: "",
		type: ["react"],
		tech: ["React"],
		ogImage: "pomodoro-clock.png",
		url: "https://apomodoroclock.netlify.com/",
		repository: "https://github.com/remusa/omodoro-clock",
	},
	{
		title: "JavaScript Calculator",
		active: true,
		description: "",
		type: ["react"],
		tech: ["React"],
		ogImage: "javascript-calculator.png",
		url: "https://ajavascriptcalculator.netlify.com/",
		repository: "https://github.com/remusa/avascript-calculator",
	},
	{
		title: "Drum Machine",
		active: true,
		description: "",
		type: ["react"],
		tech: ["React"],
		ogImage: "drum-machine.png",
		url: "https://adrummachine.netlify.com",
		repository: "https://github.com/remusa/rum-machine",
	},
	{
		title: "Markdown Previewer",
		active: true,
		description: "",
		type: ["react"],
		tech: ["React"],
		ogImage: "markdown-previewer.png",
		url: "https://amarkdownpreviewer.netlify.com/",
		repository: "https://github.com/remusa/arkdown-previewer",
	},
	{
		title: "Random Quote Generator",
		description: "Random Quote Generator",
		active: true,
		tech: ["React"],
		type: ["react"],
		ogImage: "random-quote-generator.png",
		url: "https://myrandomquotes.netlify.com/",
		repository: "https://github.com/remusa/andom-quote-machine",
	},
	{
		title: "Charts made with D3.js",
		active: true,
		description: "",
		type: ["frontend"],
		tech: ["D3.js"],
		ogImage: "data-visualization.png",
		url: "https://datavisualization.netlify.com",
		repository: "https://github.com/remusa/cc-data-visualization-projects",
	},
	{
		title: "Timestamp Microservice",
		active: true,
		description: "",
		type: ["backend"],
		tech: ["Node.js", "Express.js"],
		ogImage: "timestamp-microservice.png",
		url: "https://fcc-project-timestamp-rms.glitch.me/",
		repository: "https://github.com/remusa/oilerplate-project-timestamp",
	},
	{
		title: "Request Header Parser Microservice",
		active: true,
		description: "",
		type: ["backend"],
		tech: ["Node.js", "Express.js"],
		ogImage: "request-header-parser.png",
		url: "https://fcc-project-headerparser-rms.glitch.me",
		repository: "https://github.com/remusa/oilerplate-project-headerparser",
	},
	{
		title: "URL Shortener Microservice",
		active: true,
		description: "",
		type: ["backend"],
		tech: ["Node.js", "Express.js"],
		ogImage: "url-shortener.png",
		url: "https://fcc-project-urlshortener-rms.glitch.me/",
		repository: "https://github.com/remusa/oilerplate-project-urlshortener",
	},
	{
		title: "Exercise Tracker",
		active: true,
		description: "",
		type: ["backend"],
		tech: ["Node.js", "Express.js"],
		ogImage: "exercise-tracker.png",
		url: "https://fcc-project-exercisetracker-rms.glitch.me/",
		repository: "https://github.com/remusa/oilerplate-project-exercisetracker",
	},
	{
		title: "File Metadata Microservice",
		active: true,
		description: "",
		type: ["backend"],
		tech: ["Node.js", "Express.js"],
		ogImage: "file-metadata.png",
		url: "https://fcc-project-filemetadata-rms.glitch.me/",
		repository: "https://github.com/remusa/oilerplate-project-filemetadata",
	},
	{
		title: "Metric Imperial Converter",
		active: true,
		description: "",
		type: ["backend"],
		tech: ["Node.js", "Express.js", "Chai", "Mocha"],
		ogImage: "metric-imperial-converter.png",
		url: "https://fcc-metricimpconverter.glitch.me/",
		repository: "https://github.com/remusa/roject-metricimpconverter",
	},
	{
		title: "Issue Tracker",
		active: true,
		description: "",
		type: ["backend"],
		tech: ["Node.js", "Express.js", "Chai", "Mocha"],
		ogImage: "issue-tracker.png",
		url: "https://fcc-issuetracker-rms.glitch.me/",
		repository: "https://github.com/remusa/roject-issuetracker",
	},
	{
		title: "Personal Library",
		active: true,
		description: "",
		type: ["backend"],
		tech: ["Node.js", "Express.js", "Chai", "Mocha"],
		ogImage: "personal-library.png",
		url: "https://fcc-library-rms.glitch.me/",
		repository: "https://github.com/remusa/roject-library",
	},
	{
		title: "Stock Price Checker",
		active: true,
		description: "",
		type: ["backend"],
		tech: ["Node.js", "Express.js", "Chai", "Mocha"],
		ogImage: "stock-checker.png",
		url: "https://fcc-stockpricechecker.glitch.me/",
		repository: "https://github.com/remusa/roject-stockchecker",
	},
	{
		title: "Anonymous Message Board",
		active: true,
		description: "",
		type: ["backend"],
		tech: ["Node.js", "Express.js", "Chai", "Mocha"],
		ogImage: "message-board.png",
		url: "https://fcc-messageboard.glitch.me/",
		repository: "https://github.com/remusa/roject-messageboard",
	},
	{
		title: "Tribute Page",
		active: true,
		description: "",
		type: ["frontend"],
		tech: ["HTML5", "CSS Flexbox", "CSS Grid"],
		ogImage: "tribute-page.png",
		url: "https://tributepage.netlify.com/",
		repository: "https://github.com/remusa/ribute-page",
	},
	{
		title: "Survey Form",
		active: true,
		description: "",
		type: ["frontend"],
		tech: ["HTML5", "CSS Flexbox", "CSS Grid"],
		ogImage: "survey-form.png",
		url: "https://asurveyform.netlify.com",
		repository: "https://github.com/remusa/urvey-form",
	},
	{
		title: "Product Landing Page",
		active: true,
		description: "",
		type: ["frontend"],
		tech: ["HTML5", "CSS Flexbox", "CSS Grid"],
		ogImage: "product-landing-page.png",
		url: "https://product-landing.netlify.com/",
		repository: "https://github.com/remusa/roduct-landing-page",
	},
	{
		title: "Technical Documentation Page",
		active: true,
		description: "",
		type: ["frontend"],
		tech: ["HTML5", "CSS Flexbox", "CSS Grid", "JavaScript"],
		ogImage: "technical-documentation-page.png",
		url: "https://technical-documentation.netlify.com/",
		repository: "https://github.com/remusa/echnical-documentation-page",
	},
	{
		title: "Personal Portfolio Webpage",
		active: true,
		description: "",
		type: ["frontend"],
		tech: ["HTML5", "CSS Flexbox", "CSS Grid"],
		ogImage: "personal-portfolio.png",
		url: "https://apersonalportfolio.netlify.com/",
		repository: "https://github.com/remusa/ersonal-portfolio",
	},
];
